import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/**
 * Android entry points only: Application, Activity, the navigation foreground service, the
 * manifest and res/. Everything else — including the whole Compose UI, which is shared with iOS —
 * lives in :shared.
 *
 * This module deliberately does *not* apply the Kotlin Multiplatform plugin: that combination
 * with 'com.android.application' is deprecated in AGP 9 and removed in AGP 10.
 */
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    // Kept for the `compose.*` dependency accessors: they pin the same Compose artifacts the
    // shared module resolves, which the version catalog alone cannot do (its ui-tooling entry
    // carries no version, it relied on a BOM this project never applied).
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.baselineprofile)
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11)
    }
}

val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localProperties.load(localPropertiesFile.inputStream())
}

android {
    signingConfigs {
        create("release") {
            storeFile = localProperties.getProperty("RELEASE_STORE_FILE")?.let { rootProject.file(it) }
                ?: rootProject.file("Pelo.jks")
            storePassword = localProperties.getProperty("RELEASE_STORE_PASSWORD") ?: ""
            keyAlias = localProperties.getProperty("RELEASE_KEY_ALIAS") ?: "pelo-kmp"
            keyPassword = localProperties.getProperty("RELEASE_KEY_PASSWORD") ?: ""
        }
    }
    namespace = "eu.dotshell.pelo"
    compileSdk = 36

    defaultConfig {
        applicationId = "eu.dotshell.pelo"
        minSdk = 24
        targetSdk = 36
        versionCode = 11
        versionName = "1.1.5"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            ndk {
                debugSymbolLevel = "SYMBOL_TABLE"
            }
        }
        debug {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        compose = true
    }

    lint {
        abortOnError = false
        warningsAsErrors = false
        checkAllWarnings = false
        disable += listOf(
            "LogNotTimber",
            "UnusedAttribute",
            "GradleDependency",
            "AndroidGradlePluginVersion"
        )
    }
}

dependencies {
    implementation(project(":shared"))

    // What MainActivity, PeloApplication and NavigationModeForegroundService need directly.
    implementation(compose.runtime)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.profileinstaller)
    implementation(libs.kotlinx.coroutines.android)
    // NavigationModeForegroundService drives the fused location client itself.
    implementation(libs.google.play.services.location)

    debugImplementation(compose.uiTooling)
    // Baseline Profile generated by the :baselineprofile module. AGP merges it into the release
    // build and ProfileInstaller (already a dependency) AOT-compiles those paths on first launch.
    baselineProfile(project(":baselineprofile"))
}

val cleanCompressedAssets = tasks.register<Delete>("cleanCompressedAssets") {
    delete(layout.buildDirectory.dir("intermediates/compressed_assets"))
}

tasks.matching { it.name.startsWith("compress") && it.name.endsWith("Assets") }
    .configureEach {
        dependsOn(cleanCompressedAssets)
    }
