name: KMP CI - Pelo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # --- VERIFICATION APPLI ANDROID ---
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configurer le JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Java 17 est idéal pour compiler ton target JVM 11 avec les outils récents

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v3

      # On cible explicitement le mode Debug du module :app pour ignorer la signature manquante
      - name: Build Android (Debug)
        run: ./gradlew :app:assembleDebug

  # --- VERIFICATION APPLI IOS (Kotlin/Native) ---
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configurer le JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v3

      # Permet de vérifier que la compilation Kotlin/Native vers iOS se fait sans erreur de liaison
      - name: Build iOS Framework (Simulator)
        run: ./gradlew :app:linkDebugFrameworkIosSimulatorArm64
